# Configuration YAML pour git_push_automation

SILENT_INSTALL: 1

# Plateforme Git courante (gitlab, github, bitbucket)
platforms:
  current_platform: "github"
  github:
    repo: "teamflp/git_push_automation"